### ISSUE TITLE
Come up with Access control an encryption Scheme

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#104]
Linked issues: #90

**Comment by alvaro-alonso** [comment]
I have been reading some papers:

1. there are some papers taking about cryptographic "revocable" schemes[[1]](https://www.researchgate.net/publication/349434184_Efficient_revocable_identity-based_encryption_with_short_public_parameters). however, these seem to be still in the theoretical phase and I haven't found any implementation for them. These schemes would have been ideal for our use case. since IPFS entries are immutable, we currently not able to revoke the credentials. Once we post something encrypted in the IPFS and we give someone the keys to it. we lose completely control over the data.

2. In the paper that Jonathan posted [[2]](https://blockchainprototyping.slack.com/archives/C02L2Q1JGUQ/p1639741629001700), they proposed a forked IPFS which access is connected to an identity based smart contract. Although this solution would also serve us. forking the IPFS and implementing the proposal is out of the scope of the project.

3. So far, the only I found which we could reasonable incorporate proposed an "blockchain based Oauth 2.0" [[3]](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjczJacsvP0AhXIMewKHV__CqgQFnoECAkQAQ&url=https%3A%2F%2Farxiv.org%2Fabs%2F2001.10461&usg=AOvVaw1BFUqtLNZWu73ANxcr-Kyj). With this solution would imply that providers would have to host themselves a "resource server" for their datasets. This  resource server is connected to the blockchain and can validate with the smart contract and a JWT the validity of both conditions. So we could bring back the idea of the "provider node". 

4. The last alternative that comes into my mind, is to look a IPFS alternatives like sia or file coin and see whether these technologies have some mechanism to revoke credentials.

@kaustabhbarman @amrap030 @repype @MikeHerman19 @eliodemollari @amecklenborg

**Comment by kaustabhbarman** [comment]
I have also been thinking about a feasible solution for the access control. One of the way that we all have thought about before is encrypting the data itself in IPFS. But then we will need to provide a decryption key to the buyer. I put some more thoughts into it and tried to put things in perspective about how the process flow will actually be if we do implement it and tried to note it down:

- Provider uploads the data -> front-end generates an encryption key -> `uploadToIPFS(data)`-> CID -> front-end `encrypt(CID, encryptionKey)` -> encrypted data -> add to meta-data -> upload meta-data to IPFS and mint NFT -> store the NFT ID and encryptionKey in a conventional database 

- Buyer purchases NFT -> gets the encryption key (visible only **once**, buyer needs to save it) -> looks through purchased NFTs for his address -> selects appropriate NFT/encrypted data -> enters encryption key -> gets CID of data

For an outsider, even if he can see which NFT is owned by a random address found from the blockchain, he can never reach the CIDs of the twin data because he never got the encryption key for the NFTs metadata. 

I can explain the flow in our next call.

**Comment by alvaro-alonso** [comment]
> I have also been thinking about a feasible solution for the access control. One of the way that we all have thought about before is encrypting the data itself in IPFS. But then we will need to provide a decryption key to the buyer. I put some more thoughts into it and tried to put things in perspective about how the process flow will actually be if we do implement it and tried to note it down:
> 
>     * Provider uploads the data -> front-end generates an encryption key -> `uploadToIPFS(data)`-> CID -> front-end `encrypt(CID, encryptionKey)` -> encrypted data -> add to meta-data -> upload meta-data to IPFS and mint NFT -> store the NFT ID and encryptionKey in a conventional database
> 
>     * Buyer purchases NFT -> gets the encryption key (visible only **once**, buyer needs to save it) -> looks through purchased NFTs for his address -> selects appropriate NFT/encrypted data -> enters encryption key -> gets CID of data
> 
> 
> For an outsider, even if he can see which NFT is owned by a random address found from the blockchain, he can never reach the CIDs of the twin data because he never got the encryption key for the NFTs metadata.
> 
> I can explain the flow in our next call.

The problem with storing the data on the IPFS, even if it is hashed, is that it will stay there forever. Once we store it on the IPFS, the provider has no possibility to take it down, update, or revoke access to a user. Basically, the provider looses control over its own data.

This was the main point on the feedback we received in the mid-term presentation.

**Comment by amrap030** [comment]
Also, if you access the data via CID and decrypt it with a key, you can give anyone else the CID and the key, so he doesn't even need an account in our application.

**Comment by eliodemollari** [comment]
It will be difficult to fix the problem 100%. Once the data is accessed and downloaded, it becomes impossible to stop any consumer from re-uploading it again, aiming to be the owner of that data. 
I was thinking of using some sort of `coverage` attribute, that tells for example, for sensors of similar types in percent how much this data equals that from previously uploaded sensors. I don't know, it was just an idea that came into my mind, after reading about issues related to digital content, let me know what you guys think?

**Comment by alvaro-alonso** [comment]
> It will be difficult to fix the problem 100%. Once the data is accessed and downloaded, it becomes impossible to stop any consumer from re-uploading it again, aiming to be the owner of that data. I was thinking of using some sort of `coverage` attribute, that tells for example, for sensors of similar types in percent how much this data equals that from previously uploaded sensors. I don't know, it was just an idea that came into my mind, after reading about issues related to digital content, let me know what you guys think?

Yes, the consumer could always copy raw data and uploaded somewhere else. We can not solve that problem. But it the provider host the data in it's managed host. We can think of ways on how to limit the problem, for example with single access tokens, or tokens that expire after a certain period of time. Also the provider can decide to take down the data if he is not interested anymore. With IPFS all this mechanisms won't be possible. 

Also, a consumer won't be able to re-uploaded at least on  Taia-x since the data has to be signed by the certifier. So it is either an exact copy, which can be identified easily, or if the consumer change minimally the dataset, it has to be approved signed by the certifier.

**Comment by amrap030** [comment]
I also found something interesting in this paper: https://downloads.hindawi.com/journals/wcmc/2021/6658920.pdf

This seems to be a revocable access control mechanism based on cryptographic methods according to user attributes called CP-ABE. I haven't fully read nor understood the paper/topic, but it sounds pretty interesting. There is also a tool available in this regard, which might help: https://github.com/zeutro/openabe

This youtube video has an example: https://youtu.be/9JX7ShrUYyQ

I don't know how we could adapt this in our application and if this is suitable, but if someone is interested in this, it would be nice if you could dig into it.

Furthermore, as you already said, I don't think the problem of redistributing purchased data can be solved.

**Comment by alvaro-alonso** [comment]
> This seems to be a revocable access control mechanism based on cryptographic methods according to user attributes called CP-ABE. I haven't fully read nor understood the paper/topic, but it sounds pretty interesting. There is also a tool available in this regard, which might help: https://github.com/zeutro/openabe

CP-ABE seems to be quite interesting for our purpose. The question is whether any kind of abe algorithm is implemented on Tezos. I have asked in Tezos slack group, lets see what is the current state on the topic 🤞

**Comment by alvaro-alonso** [comment]
So I haven't found anything nor got any response regarding ABE implementations. 

I have draw a sequence diagram, of a posible process we can make:

![access_control](https://user-images.githubusercontent.com/8678242/147975622-2ecdafcd-006e-472c-8c4b-4cf0bb5dd3be.png)

1 - The provider saves its data set in a server/node, she hosts herself 
2 - and deploys a smart-contract representing the dataset
3 - The consumer buys a token for the dataset and get the token (Nr 5)
4 - The node is constantly scanning the networks and stores in the DB any new buyer of the token. (use something like Etherscan for TZS). in your experience @amrap030, would that be possible?
6 - The consumer makes a API call straight to the node and proofs (either through a zero-knowledge proof or by handing back a token given out by the smart contract that only the consumer of the transaction can know).
7 - If Authentication of Nr.6 is valid, the consumer get the dataset.


Should we meet this week and discuss which way to proceed? @kaustabhbarman @amrap030 @eliodemollari @MikeHerman19 @amecklenborg @repype
