### ISSUE TITLE
Implement access control middleware in backend

### ISSUE THREAD

**Issue by amecklenborg** [taia-x/taia-x#125]

**Comment by amrap030** [comment]
The relation between `buyer` and `nft_id` is now stored in the PostgreSQL database from the dipdup token indexer.

It is available in a table called `purchase`. The database connection should be possible with `postgresql://dipdup:changeme@db_dipdup:5433/...`

<img width="1039" alt="Bildschirmfoto 2022-01-28 um 03 32 51" src="https://user-images.githubusercontent.com/35061229/151491215-0795121e-3b11-4cd9-8c43-02880d332e8b.png">

**Comment by amrap030** [comment]
@alvaro-alonso @kaustabhbarman @amecklenborg @repype @MikeHerman19 @eliodemollari The access control for the `/download` endpoint is clear. Let's discuss here, how we handle access control for the `/upload` endpoint.

**Comment by amecklenborg** [comment]
I updated the download post request. We just need to get the tz-account of the buyer and save it in 
`pbh_of_buyer=""`
I will update the requirements.txt and docker files.
