### ISSUE TITLE
Stock Footage Research for final Presentation

### ISSUE THREAD

**Issue by amrap030** [taia-x/taia-x#139]
@alvaro-alonso @repype @eliodemollari @MikeHerman19 @kaustabhbarman @amecklenborg Please paste here some good stock footage, that you have found.

**Comment by MikeHerman19** [comment]
https://www.youtube.com/watch?v=FEeicvNSyk4 Ocean Protocol Teaser Video

**Comment by amrap030** [comment]
> https://www.youtube.com/watch?v=FEeicvNSyk4 Ocean Protocol Teaser Video

This is exactly how I imagine the teaser video, but in short :) @repype Maybe you can write the script in a similar fashion?

**Comment by amrap030** [comment]
https://youtu.be/OwnFf5oZil8

**Comment by amrap030** [comment]
https://youtu.be/ThRYF96HIzA

**Comment by kaustabhbarman** [comment]
Some royalty free musics we can use for our teaser: https://www.bensound.com/royalty-free-music/cinematic

**Comment by kaustabhbarman** [comment]
Royalty free videos: https://www.pexels.com/search/videos/technology/

**Comment by eliodemollari** [comment]
Hey guys, don't forget to consider the GAIA-x Teaser Video linked [here](https://www.data-infrastructure.eu/GAIAX/Navigation/EN/Home/home.html). I found it interesting when Jonathan first showed it at the kickoff meeting.
