### ISSUE TITLE
Create gas evaluation

### ISSUE THREAD

**Issue by repype** [taia-x/taia-x#141]
Estimate costs of all entrypoints in the smart contract

**Comment by amrap030** [comment]
Some more metrics that would be nice to evaluate:

- Gas cost
- Operational cost
- Computation overheads if there are any
- Minting duration

**Comment by repype** [comment]
### Gas costs
**Smart Contract origination**
| Action | Costs (gas) |
| ------------- |-------------|
| Smart Contract origination | 4687 |

**Entrypoints**
| Entrypoint | Costs (gas) |
| ------------- |-------------|
| buy| ... |
| mint | ... |
| transfer | ... |
| update_certs | ... |
| update_operators | ... |
| update_token_metadata | ... |
| update_user_roles | ... |
