### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by eliodemollari** [taia-x/taia-x#147]
Let's discuss here about the Evaluation chapter

**Comment by repype** [comment]
### Qualitative
- Confidentiality, Integrity, Availability (CIA Triad)
### Quantitative
- Costs: Gas, Transaction Fees
- Scalibility: Throughput*, Latency* --> Feasible?

*found [here](https://arxiv.org/pdf/1905.06852.pdf) (see Chapter 5 - Evaluation)
