### ISSUE TITLE
Backend/DevOps Research

### ISSUE THREAD

**Issue by amrap030** [taia-x/taia-x#17]
### Description

- identify what we use for off-chain storage and present how it works #24 
- think of a suitable application architecture and what components are necessary #19 
- get basic idea about CI/CD pipeline
- specify data structure for off-chain data #20
- hosting of test environment? #22  #21
- (optional/later) how do zero knowledge proofs work, what is zokrates and how does it work #23

**Comment by alvaro-alonso** [comment]
@amrap030 @kaustabhbarman @nan0k0  I am closing this ticket as I wrote for each point an issue. 

In the corresponding issues we can talk more in detail what is to be done. 

I moved #19 and #20 to sprint backlog as we should do them until next friday
