### ISSUE TITLE
Create Gaia-X Dummy Dataset (v.0.1)

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#20]

**Comment by kaustabhbarman** [comment]
I referred to a research paper "Energy Consumption Prediction of Electric Vehicles Based on Digital Twin Technology" by Zhaolong Zhang, Yuan Zou, et. al. In the paper, the digital twin model for energy consumption prediction is based on a specific electric vehicle, which mainly takes temperature factor and covers a variety of other influencing factors. A test vehicle monitoring cloud platform was used to obtain various data of the test vehicle, including **time, vehicle speed, SOC, instantaneous output voltage of the battery, instantaneous output current of the battery, acceleration pedal opening, maximum temperature of the battery pack, minimum temperature of the battery pack**, etc. 

In my opinion, these parameters can be mocked for now. However, we will still have to decide how this data will be represented on-chain. Will each datapoint be represented with a token? Or do we represent a set of data-points between a time interval? 

For now we can start working on generating a mocked data of the above parameters.

**Comment by amecklenborg** [comment]
Check the 20-dummy-dataset for detailed information. Good idea of having data regarding electrical vehicles. I will add those parameters in the module "Sensors". Exactly, each "sensordata" will be represented by a token and the sensordata is at first a JSON-file so we can work with it.

**Comment by amecklenborg** [comment]
> In my opinion, these parameters can be mocked for now. However, we will still have to decide how this data will be represented on-chain. Will each datapoint be represented with a token? Or do we represent a set of data-points between a time interval?
> 
> For now we can start working on generating a mocked data of the above parameters.
Check the 20-dummy-dataset for detailed information. Good idea of having data regarding electrical vehicles. I will add those parameters in the module "Sensors". Exactly, each "sensordata" will be represented by a token and the sensordata is at first a JSON-file so we can work with it.

**Comment by amecklenborg** [comment]
> 
> In my opinion, these parameters can be mocked for now. However, we will still have to decide how this data will be represented on-chain. Will each datapoint be represented with a token? Or do we represent a set of data-points between a time interval?
> 
> For now we can start working on generating a mocked data of the above parameters.

Check the 20-dummy-dataset branch for detailed information. Good idea of having data regarding electrical vehicles, for example batteries. I will add those parameters in the module "Sensors". Exactly, each "sensordata" will be represented by a token and the sensordata is at first a JSON-file so we can work with it. I think it is good enough for our first dummy version.
