### ISSUE TITLE
Set up `local` environment

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#21]
Set up a `local` environment for each component which is easy to set up among multiple machines:

- [x] set backend container
- [x] set frontend container
- [ ] set blockchain container
- [ ] connect all container through docker-compose
- [ ] update README.md

**Comment by alvaro-alonso** [comment]
As tezos blockchain container: https://assets.tqtezos.com/docs/setup/2-sandbox/

**Comment by amrap030** [comment]
@alvaro-alonso just out of interest, what is the use of the Postgres Database in the `docker-compose` file?

**Comment by alvaro-alonso** [comment]
@amrap030  we setup a db so we can save things there in case things have not been implemented in the smart contract. We don't know if we will finally keep it. But it is helpful for the backend that keep things in the mean time somewhere. For example, atm when we save an ontology on IPFS, the ipfs node returns a hash_id. this hash_id is the storage identifier. This should be saved in the future in the smart contract, but for now we just store it there.

And who knows maybe we find in the future other usefull uses for it.

**Comment by amrap030** [comment]
> @amrap030 we setup a db so we can save things there in case things have not been implemented in the smart contract. We don't know if we will finally keep it. But it is helpful for the backend that keep things in the mean time somewhere. For example, atm when we save an ontology on IPFS, the ipfs node returns a hash_id. this hash_id is the storage identifier. This should be saved in the future in the smart contract, but for now we just store it there.
> 
> And who knows maybe we find in the future other usefull uses for it.

Okay cool 👍🏻
