### ISSUE TITLE
Host a `staging` server

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#22]
### Description

As a Scrum Team member or Customer, I would like to get access to a staging server, so that everyone can test and review the current state of the development branch at any time.

**Comment by amrap030** [comment]
The `dev` server is intended to serve as a test environment from the current version of the development branch and should be available 24/7.

For hosting, we may use https://fleek.co/.

The following tasks are necessary:

- [ ] create development branch and work off of the development branch
- [ ] create CI/CD pipeline, that automatically deploys the test environment
- [ ] hosting

**Comment by amrap030** [comment]
Deprecated. Please reopen if we decide to reintroduce the idea of a staging environment.
