### ISSUE TITLE
Document how zk proof works

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#23]

**Comment by amecklenborg** [comment]
I would say that this is of low priority

**Comment by alvaro-alonso** [comment]
Absolutely! that is why just it is not in the sprint backlog. But I assigned it to me because I worked with Zokrates on my BA and I have extensive research material. So it will be fast 🤓

**Comment by amecklenborg** [comment]
Perfect! Looking forward to it :D

**Comment by amrap030** [comment]
Zkp's are currently not used
