### ISSUE TITLE
Epic_1: Ontology Registration (Austac Perspective)

### ISSUE THREAD

**Issue by JonathanHeiss** [taia-x/taia-x#36]
- Standards for Digital Twins are key to the success of autonomous driving. However, almost every physical asset can have a Digital Twin. This makes it hard to establish a standard.

- Addressing this problem, the Automotive Standardization Consortium (Austac) defines standardized ontologies ( data models) for Digital Twins in the context of autonomous driving. The standards are used by car manufacturers, suppliers, and others as foundation for creating and operating with Digital Twins. 
 
- Ontologies can describe different car types, e.g., passenger cars, vans , or trucks, and for different driving scenarios, e.g., motorway exit road, lane switching in urban traffic, keeping lanes in roundabouts. They determine the data structure and sensor types to be used to generate the data. To describe ontologies, the [Digital Twins Definition Language (DTDL)](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md) can be used.
 
- To establish Digital Twin ontology standards, Austac anchors them as the required data sharing format in a public data marketplace, called TAIA-X: for a dataset to be offered on the marketplace it must comply with one of the registered ontology standards. 
 
- To register its ontology standards on TAIA-X, Austac first needs to create a user account on the marketplace. Therefore, it uses the web-based interface. Once created, Austac can upload ontologies. (…)

**Comment by amrap030** [comment]
Closed because epic is split into smaller user stories in #55 #56 #57 .
