### ISSUE TITLE
Epic_2: Dataset Registration (Provider Perspective)

### ISSUE THREAD

**Issue by JonathanHeiss** [taia-x/taia-x#37]
- Alset is a car manufacturer that is currently working on Advanced Driver Assistance Systems (ADAS). For testing and developing ADAS, Alset generates data during test rides with cars that are equipped with sensors. Over time, Alset has collected a variety of datasets for different driving scenarios and car types. 

- To improve its economic situation and to establish new partnerships, Alset wants to offer this data to other interested parties. However, Alset does not know how to find suitable buyer. During an industry meetup, Alset learns about TAIA-X, an open marketplace for simulation data that relies on industry standards. 

- Alset accesses the marketplace through a web-based interface. As a first step towards offering a dataset, Alset must register a user account on the marketplace. 

- After account registration, Alset wants to offer a dataset on the marketplace. Therefore, several things are required:
1. It must prove that the dataset complies with prevailing ontology standards. Therefore, it needs to find a suitable ontology that matches its dataset. 
2. Once found, the dataset must be transformed into a token-based representation that matches the selected ontology.
3. Additionally, a dataset description in form of keywords must be uploaded.  
4. The dataset itself must be stored in a specific P2P storage system.

- After the dataset is registered and some time has passed, Alset receives a notification that another marketplace user is interested in buying the dataset. (…)

**Comment by amrap030** [comment]
Closed, because Epic is cut into smaller user stories in #44 #45 #46 #47 #48 #49 #50.
