### ISSUE TITLE
Epic_3: Finding a Dataset (Consumer Perspective)

### ISSUE THREAD

**Issue by JonathanHeiss** [taia-x/taia-x#38]
- Itnoc is an automotive system supplier that develops Advanced Driver Assistance Systems for car manufacturers.  It is currently working on Automated Lane Keeping Systems (ALKS) for trucks. 

- To instantiate the ALKS for a specific truck and to test it in different driving environments, it requires simulation data. During an industry meetup, Itnoc learns about TAIA-X, a marketplace for automotive simulation data that relies on industry standards. 

- Itnoc accesses the marketplace through a web-based interface. An integrated keyword/filter search function helps scanning through the different datasets. 

- Eventually, Itnoc finds a suitable dataset and wants to indicate its interest in buying the dataset. Therefore, it must first create a user account on the marketplace. Once created, it makes an offer. (…)

**Comment by amrap030** [comment]
Closed because epic is split into smaller user stories in #51 #52 #53 #54 .
