### ISSUE TITLE
Addendum Epic_2: Dataset and Ontology Matching

### ISSUE THREAD

**Issue by JonathanHeiss** [taia-x/taia-x#39]
- For simplicity we assume that the ontology is a data model that describes the structure of a dataset consisting of two parts: meta-data and measurements. 

![image](https://user-images.githubusercontent.com/38511013/141496701-ecc88ebb-84cb-453e-856c-ef90f40eb678.png)

- We assume that each sensor type has certain properties, e.g., data format, metrics, range, which are also defined in the ontology (data model).  If it can be verified that measurements originate from a specific sensor type, the sensor-specific properties can be determined for the measurements.

- Sensors are equipped with a certificate of their manufacturer. To prove authenticity and integrity of the measurements, each sensor signs the measurements using the certificate-related private key. By verifying the signature with the corresponding certificate, the identity of the sensor can be determined.

- In addition to the data structure, the ontology defines which sensor types must be used. To check if a dataset matches an ontology, all sensor signatures of the dataset must be verified.

**Comment by amrap030** [comment]
Closed because the process is clarified and modified.
