### ISSUE TITLE
Addendum Epic_2: Token-based Representation

### ISSUE THREAD

**Issue by JonathanHeiss** [taia-x/taia-x#40]
- As described in Epic_4, the dataset contains for each sensor measurements and meta-data. Among others, the meta-data contains the hash of the measurement.

- The hash is used to construct the signature: for better efficiency, the measurements are first hashed and then the hash is asymmetrically encrypted. Consequently, to verify the signatures, the hash is required. 

- Given that (1) the hashes are already part of the meta-data and (2) are required for on-chain signature verification anyway, they represent a good candidate for the token-based representation. Furthermore, they can be eventually be used by the data consumer to verify the integrity of the measurements. 

- Since the dataset may contain measurements of many sensors and a one-to-one mapping of token and dataset is desirable, it may make sense to aggregate the individual hash value into a single root hash that represents the dataset. Therefore, Hash Trees can be used.

**Comment by amrap030** [comment]
Closed, because the process is clarified and modified.
