### ISSUE TITLE
Choosing a programming language

### ISSUE THREAD

**Issue by repype** [taia-x/taia-x#60]
Decide for the programming language for smart contracts.

**Comment by repype** [comment]
We decided to write the smart contracts in [LIGO](https://ligolang.org/) for the following reasons:

- Broad community support
- Looks like this language is intended to be used for Tezos
- Interest in trying out a new programming language flavor
- Different variations possible (JsLIGO, CameLIGO, PascaLIGO, ReasonLIGO)

At the moment we cannot commit ourselves to it with absolute certainty. We may realize in the long run that alternative programming languages are more suitable. [SmartPy](https://smartpy.io/) may represent an alternative to [LIGO](https://ligolang.org/).

**Comment by amrap030** [comment]
@repype can we close this issue then?

**Comment by eliodemollari** [comment]
Closing issue
