### ISSUE TITLE
Create example FA2

### ISSUE THREAD

**Issue by repype** [taia-x/taia-x#62]
`FA2 - Multi-Asset Interface` proposes a standard for a unified token contract interface, supporting a wide range of token types and implementations. When it comes to the standardisation of permissions, standardisation brings the benefit of increasing trust in external smart contracts and centrally managed tokens. For this reason, FA2 standardises:
- transfer semantics,
- metadata,
- accessing balances,
- total supply, and
- permission rights

## General Tasks
- [x] Research FA2 interface
- [x] Create a basic implementation sample in the taia-x contracts directory

## Useful links
- [Introduction to Non-Fungible Tokens on Tezos Using FA2](https://assets.tqtezos.com/docs/token-contracts/fa2/2-fa2-nft-tutorial)
- [Useful collection of sample implementations](https://github.com/oxheadalpha/smart-contracts)
- [LIGO/Michelson implementation](https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-12/implementing-fa2.md)
- [SmartPy implementation](https://smartpy.io/ide?cid=QmWxgJJaWedeZHLG5dTqauAM8wcCs4yqQGkBMLvQ6Qmcuy&k=5229ded0aaece06197d9)

**Comment by eliodemollari** [comment]
Hey guys, @repype, @MikeHerman19 as we already discussed it, I would like to close this issue, do you agree?
