### ISSUE TITLE
Role-Based Access Control Using Smart Contract

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#66]
### Describtion
The role-based access control (RBAC) framework is a mechanism that describes the access control principle. As a common interaction, an organization provides a service to a user who owns a certain role that was issued by a different organization.
The RBAC-SC uses smart contracts and blockchain technology as versatile infrastructures to represent the trust and endorsement relationship that are essential in the RBAC and to realize a challenge-response authentication protocol that verifies a user’s ownership of roles

### Roles

- [ ] Consumer
- [ ] Certifier
- [ ] Provider

### Research sources 
| Description | Url |
| --- | --- |
| E.g. RBAC in Ligo Smart Contract  | [Article](https://medium.com/protofire-blog/recommendations-to-enhance-security-of-tezos-smart-contracts-d14c0e53a6d3) and [Code example](https://github.com/protofire/tezos-contracts-examples/tree/master/security) |
| Implementing a Multi-Sig Smart-Contract in Tezos; using ReasonML | [Article](https://medium.com/hackernoon/implementing-a-multi-sig-smart-contract-in-tezos-using-reasonml-1066d080eb68)
| A platform that makes use of Ethereum’s smart contract technology to realize a transorganizational utilization of roles. | [Research paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8307397)

**Comment by amrap030** [comment]
Some questions that came to my mind:

1. Do we register as individuals or as a company?
2. If we register as in individual, how can we make sure to have access to all resources of the company you are an employee of?
3. Should registration cost some tez?

**Comment by amrap030** [comment]
> ### Describtion
> The role-based access control (RBAC) framework is a mechanism that describes the access control principle. As a common interaction, an organization provides a service to a user who owns a certain role that was issued by a different organization. The RBAC-SC uses smart contracts and blockchain technology as versatile infrastructures to represent the trust and endorsement relationship that are essential in the RBAC and to realize a challenge-response authentication protocol that verifies a user’s ownership of roles
> 
> ### Roles
> * [ ]  Consumer
> * [ ]  Certifier
> * [ ]  Provider
> 
> ### Research sources
> Description	Url
> E.g. RBAC in Ligo Smart Contract	[Article](https://medium.com/protofire-blog/recommendations-to-enhance-security-of-tezos-smart-contracts-d14c0e53a6d3) and [Code example](https://github.com/protofire/tezos-contracts-examples/tree/master/security)
> Implementing a Multi-Sig Smart-Contract in Tezos; using ReasonML	[Article](https://medium.com/hackernoon/implementing-a-multi-sig-smart-contract-in-tezos-using-reasonml-1066d080eb68)
> A platform that makes use of Ethereum’s smart contract technology to realize a transorganizational utilization of roles.	[Research paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8307397)

Could you shortly describe what the Multi-Sig Smart-Contract is about? I quickly scanned the article, but I didn't quite get the idea.

**Comment by eliodemollari** [comment]
> Some questions that came to my mind:
> 
>     1. Do we register as individuals or as a company?
> 
>     2. If we register as in individual, how can we make sure to have access to all resources of the company you are an employee of?
> 
>     3. Should registration cost some tez?
> 
> 
> I currently created the following frontend components:
> 
> <img alt="Bildschirmfoto 2021-11-22 um 23 01 25" width="1424" src="https://user-images.githubusercontent.com/35061229/142941661-7689f852-12ab-4b8a-8f3d-129cc4260018.png">
> 
> The idea is, that you have to execute a transaction, after choosing one of the roles. If we implement it similar to the resources, that @alvaro-alonso provided, I think the smart contract has to implement functions like `MakeConsumer`, `MakeCertifier` and `MakeProvider`. These functions are then executed after registration and the user then automatically acts with the respective role for each following transaction.

Hey @amrap030 here are the answers to your quenstions:
1. We register as a company
2. We think that once logged in every individual  can have access to all resources of the company. 
3. The only fee that should be paid if that of storing the data into the blockchain, so yes it has to cost some tez, which I think will be paid by the wallet address that is registering. 

As you mentioned, we will provide you with the following functions in the smart contract: MakeCertifier, MakeProvider, MakeConsumer.

**Comment by eliodemollari** [comment]
> > ### Describtion
> > The role-based access control (RBAC) framework is a mechanism that describes the access control principle. As a common interaction, an organization provides a service to a user who owns a certain role that was issued by a different organization. The RBAC-SC uses smart contracts and blockchain technology as versatile infrastructures to represent the trust and endorsement relationship that are essential in the RBAC and to realize a challenge-response authentication protocol that verifies a user’s ownership of roles
> > ### Roles
> > 
> > * [ ]   Consumer
> > * [ ]   Certifier
> > * [ ]   Provider
> > 
> > ### Research sources
> > Description	Url
> > E.g. RBAC in Ligo Smart Contract	[Article](https://medium.com/protofire-blog/recommendations-to-enhance-security-of-tezos-smart-contracts-d14c0e53a6d3) and [Code example](https://github.com/protofire/tezos-contracts-examples/tree/master/security)
> > Implementing a Multi-Sig Smart-Contract in Tezos; using ReasonML	[Article](https://medium.com/hackernoon/implementing-a-multi-sig-smart-contract-in-tezos-using-reasonml-1066d080eb68)
> > A platform that makes use of Ethereum’s smart contract technology to realize a transorganizational utilization of roles.	[Research paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8307397)
> 
> Could you shortly describe what the Multi-Sig Smart-Contract is about? I quickly scanned the article, but I didn't quite get the idea.

Sorry for the confusion, it was mean to be just for us, as we had a discussion today of how we will implement the role-based access control. I would say, just ignore it and in the upcoming hours @MikeHerman19 will provide you with the implementation.
