### ISSUE TITLE
Smart Contract stores Ontology hash

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#76]
When a certifier POST a valid Ontology schema to the backend, the backend stores the schema on IPFS. IPFS then returns a hash. This hash is the unique file identifier and has to be stored in the Smart Contract for later retreaval.

-  [ ] The smart Contract keeps track stores the following information `(certifier_add: addr, ontology_hash: str, description: str)`
- [ ] `ontology_hash` and `description` are of type string and max 100 char
- [ ] `ontology_hash` should be unique accross all pairs
- [ ] an address can not have two ontology hashes with the same description

**Comment by repype** [comment]
Content addressing storage of IPFS ensures that expected content is located under a given url. [Power of content addressing](https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/avenues-for-access/lessons/power-of-content-addressing.html)

**Comment by amrap030** [comment]
We decided to store it only on IPFS, so we close this issue for now.
