### ISSUE TITLE
Backend Assert Dataset complies with Ontology

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#78]
When A providers submit the a dataset with the ontology it follows, the backend has to validate the dataset complies with the ontology before saving it to the IPFS.

For that the backend hast to create automatically a pydantic model from the Ontology schema

> ⚠️ Be aware of #39 information for dataset <> ontology matching!

**Comment by amrap030** [comment]
Closed, because it is not necessary.
