### ISSUE TITLE
Implement JWT middleware for Certifier and Provider Request

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#79]
For every incoming request regarding Certifiers / Providers, the back have to proof whether it is comming from a real Certifier or Provider. This is done with JWTs. The actual identity has to be done by the smart contract

- [ ] The backend should be able to connect to the smart contract an be able to call the identity functions
- [ ] Implement JWT middleware which calls the smart contract to proof identity.

**Comment by amrap030** [comment]
Closed, because it is not necessary.
