### ISSUE TITLE
Research how to implement provider and certifier dataset as NFT

### ISSUE THREAD

**Issue by amrap030** [taia-x/taia-x#81]
- [x] Research FA2 Interface (Functions, Datatypes, Metadata)
- [x] Evaluate if FA2 is suitable for use case/if not what are the alternatives?

**Comment by repype** [comment]
FA2 seems suitable. It provides following features which may be interesting for taia-x functionality:
- Can be designed to support a single token type (e.g. ERC-20 or ERC-721) or multiple token types (e.g. ERC-1155)
- Metadata at the token and contract level based on [TZIP-016](https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-16/tzip-16.md), especially for [uri property](https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-16/tzip-16.md#metadata-uris)
- Transfer Permission Policies (who can perform a transfer, the amount of a transfer, and who can receive tokens)
