### ISSUE TITLE
Buy Dataset as a Consumer

### ISSUE THREAD

**Issue by amrap030** [taia-x/taia-x#95]
In order to buy a dataset on the marketplace, we need the following things:

- [ ] #101
- [ ] some feedback on successful order
- [x] #102

**Comment by eliodemollari** [comment]
@amrap030 Should I create a branch for this ticket, or do you already have something opened to store my changes?

**Comment by alvaro-alonso** [comment]
We agree today (17.12) that we are implementing a simple buy until we an access control proposal (#104)
