### ISSUE TITLE
Handle multiple ownership of dataset nft

### ISSUE THREAD

**Issue by repype** [taia-x/taia-x#99]
Depending on results of #90 current smart contracts should be extended to support multiple owners of nfts and therefore enable purchasing of datasets by consumers. It has already been decided that providers should be given more permissions than consumers. Therefore, it must be possible to have at least two roles (1 provider, n consumers) modeled in the context of the nft.

- [ ]  Extend current smart contract functionalities (mint(), buy(), ...)

> Successor of #89, depending on results from #90.

**Comment by amrap030** [comment]
@repype can we close this?
